# Binance Real Account Keys (KEEP THIS SECRET!)
BINANCE_API_KEY=gnEHSt2imxAVxREG59yrWeQlcqbU0lx93UZMmC5yPQfXKzDemSjKT5YtXuXwd5jw
BINANCE_SECRET_KEY=1ylXJWZIllsBJgBL6dhLj8vaYLuKPdxgpZMZctAZ0BYac7MgPit4oCuivcuCysZE